// Action Types

//Authentication - login, signup
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const AUTH_FIELD_UPDATED = 'AUTH_FIELD_UPDATED';
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const FORM_RESET = 'FORM_RESET';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

// Create Post
export const FORM_FIELD_UPDATE = 'FORM_FIELD_UPDATE';
export const FORM_FIELD_EDITED = 'FORM_FIELD_EDITED';
export const TITLE_CHANGED = 'TITLE_CHANGED';
export const TITLE_UPDATED = 'TITLE_UPDATED';
export const DESCRIPTION_CHANGED = 'DESCRIPTION_CHANGED';
export const DESCRIPTION_UPDATED = 'DESCRIPTION_UPDATED';
export const ADD_NOTE = 'ADD_NOTE';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL';
export const EDIT_NOTE = 'EDIT_NOTE';
export const EDIT_IN_PROGRESS = 'EDIT_IN_PROGRESS';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const CANCEL_EDIT = 'CANCEL_EDIT';
export const DELETE_NOTE = 'DELETE_NOTE';

// Fetch Post
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

// Fetch Post Details
export const GET_POST_DETAILS = 'GET_POST_DETAILS';
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS';
